### ISSUE TITLE
Fix Typos in website head

### ISSUE THREAD

**Issue by AkinAguda** [AkinAguda/Fluid-Simulation-js#1]
There are a couple spelling errors in the head of the website. One in the meta and one in the page title. I believe this can negatively impact SEO and typos aren't cool :(

![Screenshot_20211031-134428_GitHub.jpg](https://user-images.githubusercontent.com/39712415/139584075-04c6511d-a49c-4a51-8cba-a677e8f04217.jpg)

See the screenshot above

**Comment by selamanse** [comment]
Hi @AkinAguda, I have tried my best in #3. I hope it is ok.

**Comment by AkinAguda** [comment]
Someone has opened a PR for this already. Thanks a lot.
